#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NusantaraSMK
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NusantaraSMKDB")]
	public partial class SMKDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Animasi(tbl_Animasi instance);
    partial void Updatetbl_Animasi(tbl_Animasi instance);
    partial void Deletetbl_Animasi(tbl_Animasi instance);
    partial void Inserttbl_Tkj(tbl_Tkj instance);
    partial void Updatetbl_Tkj(tbl_Tkj instance);
    partial void Deletetbl_Tkj(tbl_Tkj instance);
    partial void Inserttbl_CalonSiswa(tbl_CalonSiswa instance);
    partial void Updatetbl_CalonSiswa(tbl_CalonSiswa instance);
    partial void Deletetbl_CalonSiswa(tbl_CalonSiswa instance);
    partial void Inserttbl_Guru(tbl_Guru instance);
    partial void Updatetbl_Guru(tbl_Guru instance);
    partial void Deletetbl_Guru(tbl_Guru instance);
    partial void Inserttbl_Informasi(tbl_Informasi instance);
    partial void Updatetbl_Informasi(tbl_Informasi instance);
    partial void Deletetbl_Informasi(tbl_Informasi instance);
    partial void Inserttbl_Jadwal(tbl_Jadwal instance);
    partial void Updatetbl_Jadwal(tbl_Jadwal instance);
    partial void Deletetbl_Jadwal(tbl_Jadwal instance);
    partial void Inserttbl_Jawaban(tbl_Jawaban instance);
    partial void Updatetbl_Jawaban(tbl_Jawaban instance);
    partial void Deletetbl_Jawaban(tbl_Jawaban instance);
    partial void Inserttbl_Jurusan(tbl_Jurusan instance);
    partial void Updatetbl_Jurusan(tbl_Jurusan instance);
    partial void Deletetbl_Jurusan(tbl_Jurusan instance);
    partial void Inserttbl_Nilai(tbl_Nilai instance);
    partial void Updatetbl_Nilai(tbl_Nilai instance);
    partial void Deletetbl_Nilai(tbl_Nilai instance);
    partial void Inserttbl_Otomotif(tbl_Otomotif instance);
    partial void Updatetbl_Otomotif(tbl_Otomotif instance);
    partial void Deletetbl_Otomotif(tbl_Otomotif instance);
    partial void Inserttbl_Pilihan(tbl_Pilihan instance);
    partial void Updatetbl_Pilihan(tbl_Pilihan instance);
    partial void Deletetbl_Pilihan(tbl_Pilihan instance);
    partial void Inserttbl_Rpl(tbl_Rpl instance);
    partial void Updatetbl_Rpl(tbl_Rpl instance);
    partial void Deletetbl_Rpl(tbl_Rpl instance);
    partial void Inserttbl_Ruangan(tbl_Ruangan instance);
    partial void Updatetbl_Ruangan(tbl_Ruangan instance);
    partial void Deletetbl_Ruangan(tbl_Ruangan instance);
    partial void Inserttbl_Soal(tbl_Soal instance);
    partial void Updatetbl_Soal(tbl_Soal instance);
    partial void Deletetbl_Soal(tbl_Soal instance);
    partial void Inserttbl_Staf(tbl_Staf instance);
    partial void Updatetbl_Staf(tbl_Staf instance);
    partial void Deletetbl_Staf(tbl_Staf instance);
    partial void Inserttbl_Staf_Tu(tbl_Staf_Tu instance);
    partial void Updatetbl_Staf_Tu(tbl_Staf_Tu instance);
    partial void Deletetbl_Staf_Tu(tbl_Staf_Tu instance);
    #endregion
		
		public SMKDBDataContext() : 
				base(global::NusantaraSMK.Properties.Settings.Default.NusantaraSMKDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public SMKDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMKDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMKDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMKDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Animasi> tbl_Animasis
		{
			get
			{
				return this.GetTable<tbl_Animasi>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Tkj> tbl_Tkjs
		{
			get
			{
				return this.GetTable<tbl_Tkj>();
			}
		}
		
		public System.Data.Linq.Table<tbl_CalonSiswa> tbl_CalonSiswas
		{
			get
			{
				return this.GetTable<tbl_CalonSiswa>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Guru> tbl_Gurus
		{
			get
			{
				return this.GetTable<tbl_Guru>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Informasi> tbl_Informasis
		{
			get
			{
				return this.GetTable<tbl_Informasi>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Jadwal> tbl_Jadwals
		{
			get
			{
				return this.GetTable<tbl_Jadwal>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Jawaban> tbl_Jawabans
		{
			get
			{
				return this.GetTable<tbl_Jawaban>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Jurusan> tbl_Jurusans
		{
			get
			{
				return this.GetTable<tbl_Jurusan>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Nilai> tbl_Nilais
		{
			get
			{
				return this.GetTable<tbl_Nilai>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Otomotif> tbl_Otomotifs
		{
			get
			{
				return this.GetTable<tbl_Otomotif>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Pilihan> tbl_Pilihans
		{
			get
			{
				return this.GetTable<tbl_Pilihan>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Rpl> tbl_Rpls
		{
			get
			{
				return this.GetTable<tbl_Rpl>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Ruangan> tbl_Ruangans
		{
			get
			{
				return this.GetTable<tbl_Ruangan>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Soal> tbl_Soals
		{
			get
			{
				return this.GetTable<tbl_Soal>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Staf> tbl_Stafs
		{
			get
			{
				return this.GetTable<tbl_Staf>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Staf_Tu> tbl_Staf_Tus
		{
			get
			{
				return this.GetTable<tbl_Staf_Tu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Animasi")]
	public partial class tbl_Animasi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_jurusan;
		
		private EntityRef<tbl_Jurusan> _tbl_Jurusan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_jurusanChanging(int value);
    partial void Onkode_jurusanChanged();
    #endregion
		
		public tbl_Animasi()
		{
			this._tbl_Jurusan = default(EntityRef<tbl_Jurusan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_jurusan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int kode_jurusan
		{
			get
			{
				return this._kode_jurusan;
			}
			set
			{
				if ((this._kode_jurusan != value))
				{
					if (this._tbl_Jurusan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkode_jurusanChanging(value);
					this.SendPropertyChanging();
					this._kode_jurusan = value;
					this.SendPropertyChanged("kode_jurusan");
					this.Onkode_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jurusan_tbl_Animasi", Storage="_tbl_Jurusan", ThisKey="kode_jurusan", OtherKey="kode_jurusan", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Jurusan tbl_Jurusan
		{
			get
			{
				return this._tbl_Jurusan.Entity;
			}
			set
			{
				tbl_Jurusan previousValue = this._tbl_Jurusan.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Jurusan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Jurusan.Entity = null;
						previousValue.tbl_Animasi = null;
					}
					this._tbl_Jurusan.Entity = value;
					if ((value != null))
					{
						value.tbl_Animasi = this;
						this._kode_jurusan = value.kode_jurusan;
					}
					else
					{
						this._kode_jurusan = default(int);
					}
					this.SendPropertyChanged("tbl_Jurusan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Tkj")]
	public partial class tbl_Tkj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_jurusan;
		
		private EntityRef<tbl_Jurusan> _tbl_Jurusan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_jurusanChanging(int value);
    partial void Onkode_jurusanChanged();
    #endregion
		
		public tbl_Tkj()
		{
			this._tbl_Jurusan = default(EntityRef<tbl_Jurusan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_jurusan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int kode_jurusan
		{
			get
			{
				return this._kode_jurusan;
			}
			set
			{
				if ((this._kode_jurusan != value))
				{
					if (this._tbl_Jurusan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkode_jurusanChanging(value);
					this.SendPropertyChanging();
					this._kode_jurusan = value;
					this.SendPropertyChanged("kode_jurusan");
					this.Onkode_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jurusan_tbl_Tkj", Storage="_tbl_Jurusan", ThisKey="kode_jurusan", OtherKey="kode_jurusan", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Jurusan tbl_Jurusan
		{
			get
			{
				return this._tbl_Jurusan.Entity;
			}
			set
			{
				tbl_Jurusan previousValue = this._tbl_Jurusan.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Jurusan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Jurusan.Entity = null;
						previousValue.tbl_Tkj = null;
					}
					this._tbl_Jurusan.Entity = value;
					if ((value != null))
					{
						value.tbl_Tkj = this;
						this._kode_jurusan = value.kode_jurusan;
					}
					else
					{
						this._kode_jurusan = default(int);
					}
					this.SendPropertyChanged("tbl_Jurusan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CalonSiswa")]
	public partial class tbl_CalonSiswa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _no_pendaftaran;
		
		private string _password;
		
		private string _nama;
		
		private System.DateTime _tgl_lahir;
		
		private string _alamat;
		
		private string _agama;
		
		private string _email;
		
		private string _jenis_kelamin;
		
		private string _asal_sekolah;
		
		private System.Nullable<int> _kode_nilai;
		
		private System.Nullable<int> _kode_jawaban;
		
		private EntitySet<tbl_Pilihan> _tbl_Pilihans;
		
		private EntityRef<tbl_Jawaban> _tbl_Jawaban;
		
		private EntityRef<tbl_Nilai> _tbl_Nilai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onno_pendaftaranChanging(int value);
    partial void Onno_pendaftaranChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void Ontgl_lahirChanging(System.DateTime value);
    partial void Ontgl_lahirChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void OnagamaChanging(string value);
    partial void OnagamaChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onjenis_kelaminChanging(string value);
    partial void Onjenis_kelaminChanged();
    partial void Onasal_sekolahChanging(string value);
    partial void Onasal_sekolahChanged();
    partial void Onkode_nilaiChanging(System.Nullable<int> value);
    partial void Onkode_nilaiChanged();
    partial void Onkode_jawabanChanging(System.Nullable<int> value);
    partial void Onkode_jawabanChanged();
    #endregion
		
		public tbl_CalonSiswa()
		{
			this._tbl_Pilihans = new EntitySet<tbl_Pilihan>(new Action<tbl_Pilihan>(this.attach_tbl_Pilihans), new Action<tbl_Pilihan>(this.detach_tbl_Pilihans));
			this._tbl_Jawaban = default(EntityRef<tbl_Jawaban>);
			this._tbl_Nilai = default(EntityRef<tbl_Nilai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_pendaftaran", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int no_pendaftaran
		{
			get
			{
				return this._no_pendaftaran;
			}
			set
			{
				if ((this._no_pendaftaran != value))
				{
					this.Onno_pendaftaranChanging(value);
					this.SendPropertyChanging();
					this._no_pendaftaran = value;
					this.SendPropertyChanged("no_pendaftaran");
					this.Onno_pendaftaranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_lahir", DbType="Date NOT NULL")]
		public System.DateTime tgl_lahir
		{
			get
			{
				return this._tgl_lahir;
			}
			set
			{
				if ((this._tgl_lahir != value))
				{
					this.Ontgl_lahirChanging(value);
					this.SendPropertyChanging();
					this._tgl_lahir = value;
					this.SendPropertyChanged("tgl_lahir");
					this.Ontgl_lahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(100)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agama", DbType="Char(10)")]
		public string agama
		{
			get
			{
				return this._agama;
			}
			set
			{
				if ((this._agama != value))
				{
					this.OnagamaChanging(value);
					this.SendPropertyChanging();
					this._agama = value;
					this.SendPropertyChanged("agama");
					this.OnagamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_kelamin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jenis_kelamin
		{
			get
			{
				return this._jenis_kelamin;
			}
			set
			{
				if ((this._jenis_kelamin != value))
				{
					this.Onjenis_kelaminChanging(value);
					this.SendPropertyChanging();
					this._jenis_kelamin = value;
					this.SendPropertyChanged("jenis_kelamin");
					this.Onjenis_kelaminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asal_sekolah", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string asal_sekolah
		{
			get
			{
				return this._asal_sekolah;
			}
			set
			{
				if ((this._asal_sekolah != value))
				{
					this.Onasal_sekolahChanging(value);
					this.SendPropertyChanging();
					this._asal_sekolah = value;
					this.SendPropertyChanged("asal_sekolah");
					this.Onasal_sekolahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_nilai", DbType="Int")]
		public System.Nullable<int> kode_nilai
		{
			get
			{
				return this._kode_nilai;
			}
			set
			{
				if ((this._kode_nilai != value))
				{
					if (this._tbl_Nilai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkode_nilaiChanging(value);
					this.SendPropertyChanging();
					this._kode_nilai = value;
					this.SendPropertyChanged("kode_nilai");
					this.Onkode_nilaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_jawaban", DbType="Int")]
		public System.Nullable<int> kode_jawaban
		{
			get
			{
				return this._kode_jawaban;
			}
			set
			{
				if ((this._kode_jawaban != value))
				{
					if (this._tbl_Jawaban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkode_jawabanChanging(value);
					this.SendPropertyChanging();
					this._kode_jawaban = value;
					this.SendPropertyChanged("kode_jawaban");
					this.Onkode_jawabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_CalonSiswa_tbl_Pilihan", Storage="_tbl_Pilihans", ThisKey="no_pendaftaran", OtherKey="no_pendaftaran")]
		public EntitySet<tbl_Pilihan> tbl_Pilihans
		{
			get
			{
				return this._tbl_Pilihans;
			}
			set
			{
				this._tbl_Pilihans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jawaban_tbl_CalonSiswa", Storage="_tbl_Jawaban", ThisKey="kode_jawaban", OtherKey="kode_jawaban", IsForeignKey=true, DeleteRule="CASCADE")]
		public tbl_Jawaban tbl_Jawaban
		{
			get
			{
				return this._tbl_Jawaban.Entity;
			}
			set
			{
				tbl_Jawaban previousValue = this._tbl_Jawaban.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Jawaban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Jawaban.Entity = null;
						previousValue.tbl_CalonSiswas.Remove(this);
					}
					this._tbl_Jawaban.Entity = value;
					if ((value != null))
					{
						value.tbl_CalonSiswas.Add(this);
						this._kode_jawaban = value.kode_jawaban;
					}
					else
					{
						this._kode_jawaban = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Jawaban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Nilai_tbl_CalonSiswa", Storage="_tbl_Nilai", ThisKey="kode_nilai", OtherKey="kode_nilai", IsForeignKey=true, DeleteRule="CASCADE")]
		public tbl_Nilai tbl_Nilai
		{
			get
			{
				return this._tbl_Nilai.Entity;
			}
			set
			{
				tbl_Nilai previousValue = this._tbl_Nilai.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Nilai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Nilai.Entity = null;
						previousValue.tbl_CalonSiswas.Remove(this);
					}
					this._tbl_Nilai.Entity = value;
					if ((value != null))
					{
						value.tbl_CalonSiswas.Add(this);
						this._kode_nilai = value.kode_nilai;
					}
					else
					{
						this._kode_nilai = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Nilai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Pilihans(tbl_Pilihan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_CalonSiswa = this;
		}
		
		private void detach_tbl_Pilihans(tbl_Pilihan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_CalonSiswa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Guru")]
	public partial class tbl_Guru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnipChanging(int value);
    partial void OnnipChanged();
    #endregion
		
		public tbl_Guru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nip", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nip
		{
			get
			{
				return this._nip;
			}
			set
			{
				if ((this._nip != value))
				{
					this.OnnipChanging(value);
					this.SendPropertyChanging();
					this._nip = value;
					this.SendPropertyChanged("nip");
					this.OnnipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Informasi")]
	public partial class tbl_Informasi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_informasi;
		
		private string _judul;
		
		private string _isi;
		
		private System.DateTime _tanggal;
		
		private int _nip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_informasiChanging(int value);
    partial void Onkode_informasiChanged();
    partial void OnjudulChanging(string value);
    partial void OnjudulChanged();
    partial void OnisiChanging(string value);
    partial void OnisiChanged();
    partial void OntanggalChanging(System.DateTime value);
    partial void OntanggalChanged();
    partial void OnnipChanging(int value);
    partial void OnnipChanged();
    #endregion
		
		public tbl_Informasi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_informasi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kode_informasi
		{
			get
			{
				return this._kode_informasi;
			}
			set
			{
				if ((this._kode_informasi != value))
				{
					this.Onkode_informasiChanging(value);
					this.SendPropertyChanging();
					this._kode_informasi = value;
					this.SendPropertyChanged("kode_informasi");
					this.Onkode_informasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_judul", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string judul
		{
			get
			{
				return this._judul;
			}
			set
			{
				if ((this._judul != value))
				{
					this.OnjudulChanging(value);
					this.SendPropertyChanging();
					this._judul = value;
					this.SendPropertyChanged("judul");
					this.OnjudulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isi", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string isi
		{
			get
			{
				return this._isi;
			}
			set
			{
				if ((this._isi != value))
				{
					this.OnisiChanging(value);
					this.SendPropertyChanging();
					this._isi = value;
					this.SendPropertyChanged("isi");
					this.OnisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="DateTime NOT NULL")]
		public System.DateTime tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nip", DbType="Int NOT NULL")]
		public int nip
		{
			get
			{
				return this._nip;
			}
			set
			{
				if ((this._nip != value))
				{
					this.OnnipChanging(value);
					this.SendPropertyChanging();
					this._nip = value;
					this.SendPropertyChanged("nip");
					this.OnnipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Jadwal")]
	public partial class tbl_Jadwal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_jadwal;
		
		private int _kode_soal;
		
		private System.DateTime _tanggal;
		
		private int _nip;
		
		private EntityRef<tbl_Soal> _tbl_Soal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_jadwalChanging(int value);
    partial void Onkode_jadwalChanged();
    partial void Onkode_soalChanging(int value);
    partial void Onkode_soalChanged();
    partial void OntanggalChanging(System.DateTime value);
    partial void OntanggalChanged();
    partial void OnnipChanging(int value);
    partial void OnnipChanged();
    #endregion
		
		public tbl_Jadwal()
		{
			this._tbl_Soal = default(EntityRef<tbl_Soal>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_jadwal", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kode_jadwal
		{
			get
			{
				return this._kode_jadwal;
			}
			set
			{
				if ((this._kode_jadwal != value))
				{
					this.Onkode_jadwalChanging(value);
					this.SendPropertyChanging();
					this._kode_jadwal = value;
					this.SendPropertyChanged("kode_jadwal");
					this.Onkode_jadwalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_soal", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int kode_soal
		{
			get
			{
				return this._kode_soal;
			}
			set
			{
				if ((this._kode_soal != value))
				{
					if (this._tbl_Soal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkode_soalChanging(value);
					this.SendPropertyChanging();
					this._kode_soal = value;
					this.SendPropertyChanged("kode_soal");
					this.Onkode_soalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="DateTime NOT NULL")]
		public System.DateTime tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nip", DbType="Int NOT NULL")]
		public int nip
		{
			get
			{
				return this._nip;
			}
			set
			{
				if ((this._nip != value))
				{
					this.OnnipChanging(value);
					this.SendPropertyChanging();
					this._nip = value;
					this.SendPropertyChanged("nip");
					this.OnnipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Soal_tbl_Jadwal", Storage="_tbl_Soal", ThisKey="kode_soal", OtherKey="kode_soal", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Soal tbl_Soal
		{
			get
			{
				return this._tbl_Soal.Entity;
			}
			set
			{
				tbl_Soal previousValue = this._tbl_Soal.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Soal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Soal.Entity = null;
						previousValue.tbl_Jadwals.Remove(this);
					}
					this._tbl_Soal.Entity = value;
					if ((value != null))
					{
						value.tbl_Jadwals.Add(this);
						this._kode_soal = value.kode_soal;
					}
					else
					{
						this._kode_soal = default(int);
					}
					this.SendPropertyChanged("tbl_Soal");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Jawaban")]
	public partial class tbl_Jawaban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_jawaban;
		
		private string _file_jawaban;
		
		private int _kode_soal;
		
		private EntitySet<tbl_CalonSiswa> _tbl_CalonSiswas;
		
		private EntitySet<tbl_Ruangan> _tbl_Ruangans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_jawabanChanging(int value);
    partial void Onkode_jawabanChanged();
    partial void Onfile_jawabanChanging(string value);
    partial void Onfile_jawabanChanged();
    partial void Onkode_soalChanging(int value);
    partial void Onkode_soalChanged();
    #endregion
		
		public tbl_Jawaban()
		{
			this._tbl_CalonSiswas = new EntitySet<tbl_CalonSiswa>(new Action<tbl_CalonSiswa>(this.attach_tbl_CalonSiswas), new Action<tbl_CalonSiswa>(this.detach_tbl_CalonSiswas));
			this._tbl_Ruangans = new EntitySet<tbl_Ruangan>(new Action<tbl_Ruangan>(this.attach_tbl_Ruangans), new Action<tbl_Ruangan>(this.detach_tbl_Ruangans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_jawaban", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kode_jawaban
		{
			get
			{
				return this._kode_jawaban;
			}
			set
			{
				if ((this._kode_jawaban != value))
				{
					this.Onkode_jawabanChanging(value);
					this.SendPropertyChanging();
					this._kode_jawaban = value;
					this.SendPropertyChanged("kode_jawaban");
					this.Onkode_jawabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_jawaban", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string file_jawaban
		{
			get
			{
				return this._file_jawaban;
			}
			set
			{
				if ((this._file_jawaban != value))
				{
					this.Onfile_jawabanChanging(value);
					this.SendPropertyChanging();
					this._file_jawaban = value;
					this.SendPropertyChanged("file_jawaban");
					this.Onfile_jawabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_soal", DbType="Int NOT NULL")]
		public int kode_soal
		{
			get
			{
				return this._kode_soal;
			}
			set
			{
				if ((this._kode_soal != value))
				{
					this.Onkode_soalChanging(value);
					this.SendPropertyChanging();
					this._kode_soal = value;
					this.SendPropertyChanged("kode_soal");
					this.Onkode_soalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jawaban_tbl_CalonSiswa", Storage="_tbl_CalonSiswas", ThisKey="kode_jawaban", OtherKey="kode_jawaban")]
		public EntitySet<tbl_CalonSiswa> tbl_CalonSiswas
		{
			get
			{
				return this._tbl_CalonSiswas;
			}
			set
			{
				this._tbl_CalonSiswas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jawaban_tbl_Ruangan", Storage="_tbl_Ruangans", ThisKey="kode_jawaban", OtherKey="kode_jadwal")]
		public EntitySet<tbl_Ruangan> tbl_Ruangans
		{
			get
			{
				return this._tbl_Ruangans;
			}
			set
			{
				this._tbl_Ruangans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_CalonSiswas(tbl_CalonSiswa entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Jawaban = this;
		}
		
		private void detach_tbl_CalonSiswas(tbl_CalonSiswa entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Jawaban = null;
		}
		
		private void attach_tbl_Ruangans(tbl_Ruangan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Jawaban = this;
		}
		
		private void detach_tbl_Ruangans(tbl_Ruangan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Jawaban = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Jurusan")]
	public partial class tbl_Jurusan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_jurusan;
		
		private string _nama_jurusan;
		
		private string _deskripsi_jurusan;
		
		private int _kapasitas;
		
		private string _foto_jurusan;
		
		private EntityRef<tbl_Animasi> _tbl_Animasi;
		
		private EntityRef<tbl_Tkj> _tbl_Tkj;
		
		private EntityRef<tbl_Otomotif> _tbl_Otomotif;
		
		private EntityRef<tbl_Rpl> _tbl_Rpl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_jurusanChanging(int value);
    partial void Onkode_jurusanChanged();
    partial void Onnama_jurusanChanging(string value);
    partial void Onnama_jurusanChanged();
    partial void Ondeskripsi_jurusanChanging(string value);
    partial void Ondeskripsi_jurusanChanged();
    partial void OnkapasitasChanging(int value);
    partial void OnkapasitasChanged();
    partial void Onfoto_jurusanChanging(string value);
    partial void Onfoto_jurusanChanged();
    #endregion
		
		public tbl_Jurusan()
		{
			this._tbl_Animasi = default(EntityRef<tbl_Animasi>);
			this._tbl_Tkj = default(EntityRef<tbl_Tkj>);
			this._tbl_Otomotif = default(EntityRef<tbl_Otomotif>);
			this._tbl_Rpl = default(EntityRef<tbl_Rpl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_jurusan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kode_jurusan
		{
			get
			{
				return this._kode_jurusan;
			}
			set
			{
				if ((this._kode_jurusan != value))
				{
					this.Onkode_jurusanChanging(value);
					this.SendPropertyChanging();
					this._kode_jurusan = value;
					this.SendPropertyChanged("kode_jurusan");
					this.Onkode_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_jurusan", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string nama_jurusan
		{
			get
			{
				return this._nama_jurusan;
			}
			set
			{
				if ((this._nama_jurusan != value))
				{
					this.Onnama_jurusanChanging(value);
					this.SendPropertyChanging();
					this._nama_jurusan = value;
					this.SendPropertyChanged("nama_jurusan");
					this.Onnama_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deskripsi_jurusan", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string deskripsi_jurusan
		{
			get
			{
				return this._deskripsi_jurusan;
			}
			set
			{
				if ((this._deskripsi_jurusan != value))
				{
					this.Ondeskripsi_jurusanChanging(value);
					this.SendPropertyChanging();
					this._deskripsi_jurusan = value;
					this.SendPropertyChanged("deskripsi_jurusan");
					this.Ondeskripsi_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kapasitas", DbType="Int NOT NULL")]
		public int kapasitas
		{
			get
			{
				return this._kapasitas;
			}
			set
			{
				if ((this._kapasitas != value))
				{
					this.OnkapasitasChanging(value);
					this.SendPropertyChanging();
					this._kapasitas = value;
					this.SendPropertyChanged("kapasitas");
					this.OnkapasitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_jurusan", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string foto_jurusan
		{
			get
			{
				return this._foto_jurusan;
			}
			set
			{
				if ((this._foto_jurusan != value))
				{
					this.Onfoto_jurusanChanging(value);
					this.SendPropertyChanging();
					this._foto_jurusan = value;
					this.SendPropertyChanged("foto_jurusan");
					this.Onfoto_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jurusan_tbl_Animasi", Storage="_tbl_Animasi", ThisKey="kode_jurusan", OtherKey="kode_jurusan", IsUnique=true, IsForeignKey=false)]
		public tbl_Animasi tbl_Animasi
		{
			get
			{
				return this._tbl_Animasi.Entity;
			}
			set
			{
				tbl_Animasi previousValue = this._tbl_Animasi.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Animasi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Animasi.Entity = null;
						previousValue.tbl_Jurusan = null;
					}
					this._tbl_Animasi.Entity = value;
					if ((value != null))
					{
						value.tbl_Jurusan = this;
					}
					this.SendPropertyChanged("tbl_Animasi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jurusan_tbl_Tkj", Storage="_tbl_Tkj", ThisKey="kode_jurusan", OtherKey="kode_jurusan", IsUnique=true, IsForeignKey=false)]
		public tbl_Tkj tbl_Tkj
		{
			get
			{
				return this._tbl_Tkj.Entity;
			}
			set
			{
				tbl_Tkj previousValue = this._tbl_Tkj.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Tkj.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Tkj.Entity = null;
						previousValue.tbl_Jurusan = null;
					}
					this._tbl_Tkj.Entity = value;
					if ((value != null))
					{
						value.tbl_Jurusan = this;
					}
					this.SendPropertyChanged("tbl_Tkj");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jurusan_tbl_Otomotif", Storage="_tbl_Otomotif", ThisKey="kode_jurusan", OtherKey="kode_jurusan", IsUnique=true, IsForeignKey=false)]
		public tbl_Otomotif tbl_Otomotif
		{
			get
			{
				return this._tbl_Otomotif.Entity;
			}
			set
			{
				tbl_Otomotif previousValue = this._tbl_Otomotif.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Otomotif.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Otomotif.Entity = null;
						previousValue.tbl_Jurusan = null;
					}
					this._tbl_Otomotif.Entity = value;
					if ((value != null))
					{
						value.tbl_Jurusan = this;
					}
					this.SendPropertyChanged("tbl_Otomotif");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jurusan_tbl_Rpl", Storage="_tbl_Rpl", ThisKey="kode_jurusan", OtherKey="kode_jurusan", IsUnique=true, IsForeignKey=false)]
		public tbl_Rpl tbl_Rpl
		{
			get
			{
				return this._tbl_Rpl.Entity;
			}
			set
			{
				tbl_Rpl previousValue = this._tbl_Rpl.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Rpl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Rpl.Entity = null;
						previousValue.tbl_Jurusan = null;
					}
					this._tbl_Rpl.Entity = value;
					if ((value != null))
					{
						value.tbl_Jurusan = this;
					}
					this.SendPropertyChanged("tbl_Rpl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Nilai")]
	public partial class tbl_Nilai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_nilai;
		
		private int _kode_soal;
		
		private EntitySet<tbl_CalonSiswa> _tbl_CalonSiswas;
		
		private EntityRef<tbl_Soal> _tbl_Soal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_nilaiChanging(int value);
    partial void Onkode_nilaiChanged();
    partial void Onkode_soalChanging(int value);
    partial void Onkode_soalChanged();
    #endregion
		
		public tbl_Nilai()
		{
			this._tbl_CalonSiswas = new EntitySet<tbl_CalonSiswa>(new Action<tbl_CalonSiswa>(this.attach_tbl_CalonSiswas), new Action<tbl_CalonSiswa>(this.detach_tbl_CalonSiswas));
			this._tbl_Soal = default(EntityRef<tbl_Soal>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_nilai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kode_nilai
		{
			get
			{
				return this._kode_nilai;
			}
			set
			{
				if ((this._kode_nilai != value))
				{
					this.Onkode_nilaiChanging(value);
					this.SendPropertyChanging();
					this._kode_nilai = value;
					this.SendPropertyChanged("kode_nilai");
					this.Onkode_nilaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_soal", DbType="Int NOT NULL")]
		public int kode_soal
		{
			get
			{
				return this._kode_soal;
			}
			set
			{
				if ((this._kode_soal != value))
				{
					if (this._tbl_Soal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkode_soalChanging(value);
					this.SendPropertyChanging();
					this._kode_soal = value;
					this.SendPropertyChanged("kode_soal");
					this.Onkode_soalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Nilai_tbl_CalonSiswa", Storage="_tbl_CalonSiswas", ThisKey="kode_nilai", OtherKey="kode_nilai")]
		public EntitySet<tbl_CalonSiswa> tbl_CalonSiswas
		{
			get
			{
				return this._tbl_CalonSiswas;
			}
			set
			{
				this._tbl_CalonSiswas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Soal_tbl_Nilai", Storage="_tbl_Soal", ThisKey="kode_soal", OtherKey="kode_soal", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Soal tbl_Soal
		{
			get
			{
				return this._tbl_Soal.Entity;
			}
			set
			{
				tbl_Soal previousValue = this._tbl_Soal.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Soal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Soal.Entity = null;
						previousValue.tbl_Nilais.Remove(this);
					}
					this._tbl_Soal.Entity = value;
					if ((value != null))
					{
						value.tbl_Nilais.Add(this);
						this._kode_soal = value.kode_soal;
					}
					else
					{
						this._kode_soal = default(int);
					}
					this.SendPropertyChanged("tbl_Soal");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_CalonSiswas(tbl_CalonSiswa entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Nilai = this;
		}
		
		private void detach_tbl_CalonSiswas(tbl_CalonSiswa entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Nilai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Otomotif")]
	public partial class tbl_Otomotif : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_jurusan;
		
		private EntityRef<tbl_Jurusan> _tbl_Jurusan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_jurusanChanging(int value);
    partial void Onkode_jurusanChanged();
    #endregion
		
		public tbl_Otomotif()
		{
			this._tbl_Jurusan = default(EntityRef<tbl_Jurusan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_jurusan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int kode_jurusan
		{
			get
			{
				return this._kode_jurusan;
			}
			set
			{
				if ((this._kode_jurusan != value))
				{
					if (this._tbl_Jurusan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkode_jurusanChanging(value);
					this.SendPropertyChanging();
					this._kode_jurusan = value;
					this.SendPropertyChanged("kode_jurusan");
					this.Onkode_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jurusan_tbl_Otomotif", Storage="_tbl_Jurusan", ThisKey="kode_jurusan", OtherKey="kode_jurusan", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Jurusan tbl_Jurusan
		{
			get
			{
				return this._tbl_Jurusan.Entity;
			}
			set
			{
				tbl_Jurusan previousValue = this._tbl_Jurusan.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Jurusan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Jurusan.Entity = null;
						previousValue.tbl_Otomotif = null;
					}
					this._tbl_Jurusan.Entity = value;
					if ((value != null))
					{
						value.tbl_Otomotif = this;
						this._kode_jurusan = value.kode_jurusan;
					}
					else
					{
						this._kode_jurusan = default(int);
					}
					this.SendPropertyChanged("tbl_Jurusan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Pilihan")]
	public partial class tbl_Pilihan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_pilihan;
		
		private int _no_pendaftaran;
		
		private string _prioritas1;
		
		private string _prioritas2;
		
		private string _prioritas3;
		
		private EntityRef<tbl_CalonSiswa> _tbl_CalonSiswa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_pilihanChanging(int value);
    partial void Onkode_pilihanChanged();
    partial void Onno_pendaftaranChanging(int value);
    partial void Onno_pendaftaranChanged();
    partial void Onprioritas1Changing(string value);
    partial void Onprioritas1Changed();
    partial void Onprioritas2Changing(string value);
    partial void Onprioritas2Changed();
    partial void Onprioritas3Changing(string value);
    partial void Onprioritas3Changed();
    #endregion
		
		public tbl_Pilihan()
		{
			this._tbl_CalonSiswa = default(EntityRef<tbl_CalonSiswa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_pilihan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kode_pilihan
		{
			get
			{
				return this._kode_pilihan;
			}
			set
			{
				if ((this._kode_pilihan != value))
				{
					this.Onkode_pilihanChanging(value);
					this.SendPropertyChanging();
					this._kode_pilihan = value;
					this.SendPropertyChanged("kode_pilihan");
					this.Onkode_pilihanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_pendaftaran", DbType="Int NOT NULL")]
		public int no_pendaftaran
		{
			get
			{
				return this._no_pendaftaran;
			}
			set
			{
				if ((this._no_pendaftaran != value))
				{
					if (this._tbl_CalonSiswa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onno_pendaftaranChanging(value);
					this.SendPropertyChanging();
					this._no_pendaftaran = value;
					this.SendPropertyChanged("no_pendaftaran");
					this.Onno_pendaftaranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prioritas1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prioritas1
		{
			get
			{
				return this._prioritas1;
			}
			set
			{
				if ((this._prioritas1 != value))
				{
					this.Onprioritas1Changing(value);
					this.SendPropertyChanging();
					this._prioritas1 = value;
					this.SendPropertyChanged("prioritas1");
					this.Onprioritas1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prioritas2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prioritas2
		{
			get
			{
				return this._prioritas2;
			}
			set
			{
				if ((this._prioritas2 != value))
				{
					this.Onprioritas2Changing(value);
					this.SendPropertyChanging();
					this._prioritas2 = value;
					this.SendPropertyChanged("prioritas2");
					this.Onprioritas2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prioritas3", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prioritas3
		{
			get
			{
				return this._prioritas3;
			}
			set
			{
				if ((this._prioritas3 != value))
				{
					this.Onprioritas3Changing(value);
					this.SendPropertyChanging();
					this._prioritas3 = value;
					this.SendPropertyChanged("prioritas3");
					this.Onprioritas3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_CalonSiswa_tbl_Pilihan", Storage="_tbl_CalonSiswa", ThisKey="no_pendaftaran", OtherKey="no_pendaftaran", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_CalonSiswa tbl_CalonSiswa
		{
			get
			{
				return this._tbl_CalonSiswa.Entity;
			}
			set
			{
				tbl_CalonSiswa previousValue = this._tbl_CalonSiswa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_CalonSiswa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_CalonSiswa.Entity = null;
						previousValue.tbl_Pilihans.Remove(this);
					}
					this._tbl_CalonSiswa.Entity = value;
					if ((value != null))
					{
						value.tbl_Pilihans.Add(this);
						this._no_pendaftaran = value.no_pendaftaran;
					}
					else
					{
						this._no_pendaftaran = default(int);
					}
					this.SendPropertyChanged("tbl_CalonSiswa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Rpl")]
	public partial class tbl_Rpl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_jurusan;
		
		private EntityRef<tbl_Jurusan> _tbl_Jurusan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_jurusanChanging(int value);
    partial void Onkode_jurusanChanged();
    #endregion
		
		public tbl_Rpl()
		{
			this._tbl_Jurusan = default(EntityRef<tbl_Jurusan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_jurusan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int kode_jurusan
		{
			get
			{
				return this._kode_jurusan;
			}
			set
			{
				if ((this._kode_jurusan != value))
				{
					if (this._tbl_Jurusan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkode_jurusanChanging(value);
					this.SendPropertyChanging();
					this._kode_jurusan = value;
					this.SendPropertyChanged("kode_jurusan");
					this.Onkode_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jurusan_tbl_Rpl", Storage="_tbl_Jurusan", ThisKey="kode_jurusan", OtherKey="kode_jurusan", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Jurusan tbl_Jurusan
		{
			get
			{
				return this._tbl_Jurusan.Entity;
			}
			set
			{
				tbl_Jurusan previousValue = this._tbl_Jurusan.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Jurusan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Jurusan.Entity = null;
						previousValue.tbl_Rpl = null;
					}
					this._tbl_Jurusan.Entity = value;
					if ((value != null))
					{
						value.tbl_Rpl = this;
						this._kode_jurusan = value.kode_jurusan;
					}
					else
					{
						this._kode_jurusan = default(int);
					}
					this.SendPropertyChanged("tbl_Jurusan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Ruangan")]
	public partial class tbl_Ruangan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_ruangan;
		
		private int _kode_jadwal;
		
		private int _kode_soal;
		
		private System.Nullable<int> _kapasitas;
		
		private EntityRef<tbl_Jawaban> _tbl_Jawaban;
		
		private EntityRef<tbl_Soal> _tbl_Soal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_ruanganChanging(int value);
    partial void Onkode_ruanganChanged();
    partial void Onkode_jadwalChanging(int value);
    partial void Onkode_jadwalChanged();
    partial void Onkode_soalChanging(int value);
    partial void Onkode_soalChanged();
    partial void OnkapasitasChanging(System.Nullable<int> value);
    partial void OnkapasitasChanged();
    #endregion
		
		public tbl_Ruangan()
		{
			this._tbl_Jawaban = default(EntityRef<tbl_Jawaban>);
			this._tbl_Soal = default(EntityRef<tbl_Soal>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_ruangan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kode_ruangan
		{
			get
			{
				return this._kode_ruangan;
			}
			set
			{
				if ((this._kode_ruangan != value))
				{
					this.Onkode_ruanganChanging(value);
					this.SendPropertyChanging();
					this._kode_ruangan = value;
					this.SendPropertyChanged("kode_ruangan");
					this.Onkode_ruanganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_jadwal", DbType="Int NOT NULL")]
		public int kode_jadwal
		{
			get
			{
				return this._kode_jadwal;
			}
			set
			{
				if ((this._kode_jadwal != value))
				{
					if (this._tbl_Jawaban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkode_jadwalChanging(value);
					this.SendPropertyChanging();
					this._kode_jadwal = value;
					this.SendPropertyChanged("kode_jadwal");
					this.Onkode_jadwalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_soal", DbType="Int NOT NULL")]
		public int kode_soal
		{
			get
			{
				return this._kode_soal;
			}
			set
			{
				if ((this._kode_soal != value))
				{
					if (this._tbl_Soal.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkode_soalChanging(value);
					this.SendPropertyChanging();
					this._kode_soal = value;
					this.SendPropertyChanged("kode_soal");
					this.Onkode_soalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kapasitas", DbType="Int")]
		public System.Nullable<int> kapasitas
		{
			get
			{
				return this._kapasitas;
			}
			set
			{
				if ((this._kapasitas != value))
				{
					this.OnkapasitasChanging(value);
					this.SendPropertyChanging();
					this._kapasitas = value;
					this.SendPropertyChanged("kapasitas");
					this.OnkapasitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Jawaban_tbl_Ruangan", Storage="_tbl_Jawaban", ThisKey="kode_jadwal", OtherKey="kode_jawaban", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Jawaban tbl_Jawaban
		{
			get
			{
				return this._tbl_Jawaban.Entity;
			}
			set
			{
				tbl_Jawaban previousValue = this._tbl_Jawaban.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Jawaban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Jawaban.Entity = null;
						previousValue.tbl_Ruangans.Remove(this);
					}
					this._tbl_Jawaban.Entity = value;
					if ((value != null))
					{
						value.tbl_Ruangans.Add(this);
						this._kode_jadwal = value.kode_jawaban;
					}
					else
					{
						this._kode_jadwal = default(int);
					}
					this.SendPropertyChanged("tbl_Jawaban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Soal_tbl_Ruangan", Storage="_tbl_Soal", ThisKey="kode_soal", OtherKey="kode_soal", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_Soal tbl_Soal
		{
			get
			{
				return this._tbl_Soal.Entity;
			}
			set
			{
				tbl_Soal previousValue = this._tbl_Soal.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Soal.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Soal.Entity = null;
						previousValue.tbl_Ruangans.Remove(this);
					}
					this._tbl_Soal.Entity = value;
					if ((value != null))
					{
						value.tbl_Ruangans.Add(this);
						this._kode_soal = value.kode_soal;
					}
					else
					{
						this._kode_soal = default(int);
					}
					this.SendPropertyChanged("tbl_Soal");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Soal")]
	public partial class tbl_Soal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kode_soal;
		
		private string _file_soal;
		
		private EntitySet<tbl_Jadwal> _tbl_Jadwals;
		
		private EntitySet<tbl_Nilai> _tbl_Nilais;
		
		private EntitySet<tbl_Ruangan> _tbl_Ruangans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkode_soalChanging(int value);
    partial void Onkode_soalChanged();
    partial void Onfile_soalChanging(string value);
    partial void Onfile_soalChanged();
    #endregion
		
		public tbl_Soal()
		{
			this._tbl_Jadwals = new EntitySet<tbl_Jadwal>(new Action<tbl_Jadwal>(this.attach_tbl_Jadwals), new Action<tbl_Jadwal>(this.detach_tbl_Jadwals));
			this._tbl_Nilais = new EntitySet<tbl_Nilai>(new Action<tbl_Nilai>(this.attach_tbl_Nilais), new Action<tbl_Nilai>(this.detach_tbl_Nilais));
			this._tbl_Ruangans = new EntitySet<tbl_Ruangan>(new Action<tbl_Ruangan>(this.attach_tbl_Ruangans), new Action<tbl_Ruangan>(this.detach_tbl_Ruangans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_soal", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kode_soal
		{
			get
			{
				return this._kode_soal;
			}
			set
			{
				if ((this._kode_soal != value))
				{
					this.Onkode_soalChanging(value);
					this.SendPropertyChanging();
					this._kode_soal = value;
					this.SendPropertyChanged("kode_soal");
					this.Onkode_soalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_soal", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string file_soal
		{
			get
			{
				return this._file_soal;
			}
			set
			{
				if ((this._file_soal != value))
				{
					this.Onfile_soalChanging(value);
					this.SendPropertyChanging();
					this._file_soal = value;
					this.SendPropertyChanged("file_soal");
					this.Onfile_soalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Soal_tbl_Jadwal", Storage="_tbl_Jadwals", ThisKey="kode_soal", OtherKey="kode_soal")]
		public EntitySet<tbl_Jadwal> tbl_Jadwals
		{
			get
			{
				return this._tbl_Jadwals;
			}
			set
			{
				this._tbl_Jadwals.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Soal_tbl_Nilai", Storage="_tbl_Nilais", ThisKey="kode_soal", OtherKey="kode_soal")]
		public EntitySet<tbl_Nilai> tbl_Nilais
		{
			get
			{
				return this._tbl_Nilais;
			}
			set
			{
				this._tbl_Nilais.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Soal_tbl_Ruangan", Storage="_tbl_Ruangans", ThisKey="kode_soal", OtherKey="kode_soal")]
		public EntitySet<tbl_Ruangan> tbl_Ruangans
		{
			get
			{
				return this._tbl_Ruangans;
			}
			set
			{
				this._tbl_Ruangans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Jadwals(tbl_Jadwal entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Soal = this;
		}
		
		private void detach_tbl_Jadwals(tbl_Jadwal entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Soal = null;
		}
		
		private void attach_tbl_Nilais(tbl_Nilai entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Soal = this;
		}
		
		private void detach_tbl_Nilais(tbl_Nilai entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Soal = null;
		}
		
		private void attach_tbl_Ruangans(tbl_Ruangan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Soal = this;
		}
		
		private void detach_tbl_Ruangans(tbl_Ruangan entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Soal = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Staf")]
	public partial class tbl_Staf : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _kode_karyawan;
		
		private int _nip;
		
		private string _password;
		
		private string _nama;
		
		private System.DateTime _tgl_lahir;
		
		private string _alamat;
		
		private string _agama;
		
		private string _email;
		
		private string _jenis_kelamin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onkode_karyawanChanging(string value);
    partial void Onkode_karyawanChanged();
    partial void OnnipChanging(int value);
    partial void OnnipChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void Ontgl_lahirChanging(System.DateTime value);
    partial void Ontgl_lahirChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void OnagamaChanging(string value);
    partial void OnagamaChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onjenis_kelaminChanging(string value);
    partial void Onjenis_kelaminChanged();
    #endregion
		
		public tbl_Staf()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_karyawan", AutoSync=AutoSync.Always, DbType="VarChar(9)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string kode_karyawan
		{
			get
			{
				return this._kode_karyawan;
			}
			set
			{
				if ((this._kode_karyawan != value))
				{
					this.Onkode_karyawanChanging(value);
					this.SendPropertyChanging();
					this._kode_karyawan = value;
					this.SendPropertyChanged("kode_karyawan");
					this.Onkode_karyawanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nip", DbType="Int NOT NULL")]
		public int nip
		{
			get
			{
				return this._nip;
			}
			set
			{
				if ((this._nip != value))
				{
					this.OnnipChanging(value);
					this.SendPropertyChanging();
					this._nip = value;
					this.SendPropertyChanged("nip");
					this.OnnipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_lahir", DbType="Date NOT NULL")]
		public System.DateTime tgl_lahir
		{
			get
			{
				return this._tgl_lahir;
			}
			set
			{
				if ((this._tgl_lahir != value))
				{
					this.Ontgl_lahirChanging(value);
					this.SendPropertyChanging();
					this._tgl_lahir = value;
					this.SendPropertyChanged("tgl_lahir");
					this.Ontgl_lahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agama", DbType="Char(10)")]
		public string agama
		{
			get
			{
				return this._agama;
			}
			set
			{
				if ((this._agama != value))
				{
					this.OnagamaChanging(value);
					this.SendPropertyChanging();
					this._agama = value;
					this.SendPropertyChanged("agama");
					this.OnagamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_kelamin", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string jenis_kelamin
		{
			get
			{
				return this._jenis_kelamin;
			}
			set
			{
				if ((this._jenis_kelamin != value))
				{
					this.Onjenis_kelaminChanging(value);
					this.SendPropertyChanging();
					this._jenis_kelamin = value;
					this.SendPropertyChanged("jenis_kelamin");
					this.Onjenis_kelaminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Staf_Tu")]
	public partial class tbl_Staf_Tu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnipChanging(int value);
    partial void OnnipChanged();
    #endregion
		
		public tbl_Staf_Tu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nip", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nip
		{
			get
			{
				return this._nip;
			}
			set
			{
				if ((this._nip != value))
				{
					this.OnnipChanging(value);
					this.SendPropertyChanging();
					this._nip = value;
					this.SendPropertyChanged("nip");
					this.OnnipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
